### ISSUE TITLE
panic: pmap_page_exists_quick while building pkg

### ISSUE THREAD

**Issue by emaste** [FreeBSDFoundation/freebsd#16]
checking whether cc accepts -g... panic: pmap_page_exists_quick
cpuid = 0
KDB: stack backtrace:
db_trace_self() at db_trace_self_wrapper+0x28
         pc = 0xffffff80003e5008  lr = 0xffffff8000017b44
         sp = 0xffffff8056fbd820  fp = 0xffffff8056fbd940

db_trace_self_wrapper() at vpanic+0x1a0
         pc = 0xffffff8000017b44  lr = 0xffffff800016a970
         sp = 0xffffff8056fbd950  fp = 0xffffff8056fbd9c0

vpanic() at panic+0x4c
         pc = 0xffffff800016a970  lr = 0xffffff800016aa20
         sp = 0xffffff8056fbd9d0  fp = 0xffffff8056fbda50

panic() at pmap_page_exists_quick+0x18
         pc = 0xffffff800016aa20  lr = 0xffffff80003f1738
         sp = 0xffffff8056fbda60  fp = 0xffffff8056fbda60

pmap_page_exists_quick() at vm_pageout_object_deactivate_pages+0x1e8
         pc = 0xffffff80003f1738  lr = 0xffffff80003d3cf4
         sp = 0xffffff8056fbda70  fp = 0xffffff8056fbdae0

vm_pageout_object_deactivate_pages() at vm_daemon+0x2a0
         pc = 0xffffff80003d3cf4  lr = 0xffffff80003d39dc
         sp = 0xffffff8056fbdaf0  fp = 0xffffff8056fbdb70

vm_daemon() at fork_exit+0x88
         pc = 0xffffff80003d39dc  lr = 0xffffff8000134ce8
         sp = 0xffffff8056fbdb80  fp = 0xffffff8056fbdbb0

fork_exit() at fork_trampoline+0x10
         pc = 0xffffff8000134ce8  lr = 0xffffff80003f3f34
         sp = 0xffffff8056fbdbc0  fp = 0x00000000

KDB: enter: panic
[ thread pid 4 tid 100025 ]
Stopped at      kdb_enter+0x6c:
db>

**Comment by zxombie** [comment]
Should be fixed by 679469175518c5c563a50668dde0236f0382f69c
