### ISSUE TITLE
need cpu_set_upcall_kse implementation

### ISSUE THREAD

**Issue by emaste** [FreeBSDFoundation/freebsd#24]
starting lldb triggers a panic

root@:~ # lldb
panic: ARM64TODO: cpu_set_upcall_kse
KDB: stack backtrace:
db_trace_self() at db_trace_self_wrapper+0x28
         pc = 0xffffff800037fdd8  lr = 0xffffff800001730c
         sp = 0xffffff80c5d0e680  fp = 0xffffff80c5d0e7a0

db_trace_self_wrapper() at vpanic+0xa4
         pc = 0xffffff800001730c  lr = 0xffffff800013ca98
         sp = 0xffffff80c5d0e7b0  fp = 0xffffff80c5d0e820

vpanic() at panic+0x4c
         pc = 0xffffff800013ca98  lr = 0xffffff800013cb7c
         sp = 0xffffff80c5d0e830  fp = 0xffffff80c5d0e8b0

panic() at cpu_set_upcall_kse+0x10
         pc = 0xffffff800013cb7c  lr = 0xffffff800038b704
         sp = 0xffffff80c5d0e8c0  fp = 0xffffff80c5d0e8c0

cpu_set_upcall_kse() at create_thread+0x194
         pc = 0xffffff800038b704  lr = 0xffffff800014ac6c
         sp = 0xffffff80c5d0e8d0  fp = 0xffffff80c5d0e950

create_thread() at sys_thr_new+0x8c
         pc = 0xffffff800014ac6c  lr = 0xffffff800014ae90
         sp = 0xffffff80c5d0e960  fp = 0xffffff80c5d0e9f0

sys_thr_new() at do_el0_sync+0x2e8
         pc = 0xffffff800014ae90  lr = 0xffffff800038ad40
         sp = 0xffffff80c5d0ea00  fp = 0xffffff80c5d0eaa0

do_el0_sync() at handle_el0_sync+0x58
         pc = 0xffffff800038ad40  lr = 0xffffff80003811bc
         sp = 0xffffff80c5d0eab0  fp = 0x0000007ffffff728

handle_el0_sync() at 0x53cda8
         pc = 0xffffff80003811bc  lr = 0x000000000053cda8
         sp = 0x0000007ffffff738  fp = 0x0000007ffffff7b8

$d.6() at 0x485634
         pc = 0x000000000053cda8  lr = 0x0000000000485634
         sp = 0x0000007ffffff7c8  fp = 0x0000007ffffff898

$d.6() at 0x55bc50
         pc = 0x0000000000485634  lr = 0x000000000055bc50
         sp = 0x0000007ffffff8a8  fp = 0x0000007ffffff8d8

$d.6() at 0x41188c
         pc = 0x000000000055bc50  lr = 0x000000000041188c
         sp = 0x0000007ffffff8e8  fp = 0x0000007ffffff908

$d.6() at 0x40e4c0
         pc = 0x000000000041188c  lr = 0x000000000040e4c0
         sp = 0x0000007ffffff918  fp = 0x0000007ffffffa28

$d.6() at 0x40e99c
         pc = 0x000000000040e4c0  lr = 0x000000000040e99c
         sp = 0x0000007ffffffa38  fp = 0x0000007ffffffba8

$d.6() at 0x40c17c
         pc = 0x000000000040e99c  lr = 0x000000000040c17c
         sp = 0x0000007ffffffbb8  fp = 0x0000007ffffffbe8

$d.6() at 0x42608424
         pc = 0x000000000040c17c  lr = 0x0000000042608424
         sp = 0x0000007ffffffbf8  fp = 0x0000000000000000

**Comment by zxombie** [comment]
Fixed in r285171
