### ISSUE TITLE
Get truss building on arm64

### ISSUE THREAD

**Issue by zxombie** [FreeBSDFoundation/freebsd#6]
There is no support for arm64.

**Comment by emaste** [comment]
That is, we need a aarch64-fbsd.c.

The existing ones have all been copied from one arch to the next and then updated. mips-fbsd.c claims to be "FreeBSD/sparc64-specific system call handling" and says "This file is almost nothing more than a slightly-edited i386-fbsd.c."

**Comment by emaste** [comment]
Fixed by @kostikbel in r288493
https://svnweb.freebsd.org/changeset/base/288493
